---
env:
  jquery: true
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'eslint-config-prettier'
  - 'plugin:prettier/recommended'
  - './node_modules/@typhonjs-fvtt/eslint-foundry.js/config/latest/.eslintrc'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json
plugins:
  - prettier
  - "@typescript-eslint"
rules:
  #Fvtt support
  no-shadow: off
  '@typescript-eslint/no-shadow': [ "error", { "builtinGlobals": true, "hoist": "all", "allow": [ "event" ] } ]

  #Personal preferences
  prettier/prettier: error
  semi: warn
  curly: warn
  brace-style: 1
  indent: [ "warn", 2, { "SwitchCase": 1 } ]

